### ISSUE TITLE
[`Acknowledgement`] : Thanks for creating this.

### ISSUE THREAD

**Issue by baseplate-admin** [snowdrop4/acornserver#1]
Hi there,

it seems you have a complete Tracker implementation ( but in django ? ) Thats really cool ( NGL i was lookin for somethin like this for a long time )

Would you mind if i reuse some of your code ( specially the tracker part in [this project](https://github.com/baseplate-admin/CoreProject) ? ) 

Once again thanks for creating something cool :D

**Comment by snowdrop4** [comment]
No problem. Feel free to use whatever!

**Comment by baseplate-admin** [comment]
Thank you :D 

Have a nice day. 

( if you dont mind me asking did you follow any tutorials / resources while creating this ? )

**Comment by snowdrop4** [comment]
Not really. I just looked at the [bittorrent specifications](https://www.bittorrent.org/beps/bep_0003.html) and the Django docs and made it up as I went along.
